var t = '';
t += '<div id="tip" class="popover tip" role="tooltip">';
t += '<div class="content">';
t += '<h3 class="title">Solution Title</h3>';
t += '<p><em class="type">Prevention Solution</em></p>';
t += '<p class="stat economic-value-per-ton">';
t += '<strong>$<span>XXX</span></strong>';
t += '<small>m/year<br>';
t += 'Business Profit Potential</small>';
t += '</p>';
t += '<p class="stat diversion-potential">';
t += '<strong><span>XXX</span>M</strong>';
t += '<small>tons/year<br>';
t += 'in Diversion Potential</small>';
t += '</p>';
t += '<p class="stat meals-recovered">';
t += '<strong><span>XXX</span>M</strong>';
t += '<small>meals/year<br>';
t += 'Meals Recovered</small>';
t += '</p>';
t += '<p class="stat emission-reduction">';
t += '<strong><span>XXX</span>K</strong>';
t += '<small>tons/year<br>';
t += 'in GHGs emission reduction</small>';
t += '</p>';
t += '<p class="stat water-conservation">';
t += '<strong><span>XXX</span>B</strong>';
t += '<small>gal/year<br>';
t += 'in water conservation</small>';
t += '</p>';
t += '<p class="stat jobs-create">';
t += '<strong><span>XXX</span></strong>';
t += '<small>jobs created</small>';
t += '</p>';
t += '<p class="summary">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod';
t += 'tempor incididunt ut labore et dolore magna aliqua.</p>';
t += '</div>';
t += '<a href="#" class="button">View more information &nbsp;&gt;</a>';
t += '</div>';