# Site settings
title: ReFED | Rethink Food Waste
email: info@refed.com
description:  "A data-driven guide for businesses, government, funders, and nonprofits to collectively reduce food waste at scale. Together, we can reduce U.S. food waste by 50% by 2030."
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://dev.refed.com" # the base hostname & protocol for your site

collections:
  solutions:
    output: true
    layout: default
    permalink: /solutions/:path
  stakeholders:
    output: true
    layout: default
    permalink: /stakeholders/:path
  tools:
    output: true
    layout: tool
    permalink: /tools/:path
  states:
    output: true
    layout: state
    permalink: /tools/food-waste-policy-finder/states/:path
  innovators:
    output: true
    layout: innovator
    permalink: /tools/innovator-database/:path
  articles:
    output: true
    layout: article
    permalink: /content-hub/:path

defaults:
- scope:
    path: "_states/"
    type: 'states'
  values:
    layout: state
    header: "<small>U.S. Food Waste</small>Policy Finder"
- scope:
    path: "_solutions/"
    type: 'solutions'
  values:
    nextpage:
      url: /stakeholder
      title: Stakeholders
    prevpage:
      url: /solution
      title: Solutions
- scope:
    path: "_stakeholders/"
    type: 'stakeholders'
  values:
    nextpage:
      url: /action
      title: Action
    prevpage:
      url: /stakeholder
      title: Stakeholders






# Build settings
safe: false
source: src
markdown: kramdown

include: ["_pages"]
exclude: 
  - _tools/policy-tool/_partials


gems:
  - jekyll-last-modified-at
  - jekyll-contentblocks
# - jekyll-lunr-js-search


# Cloudcannon Editor
reach:
  - Local
  - National

food_recovery_hierarchy:
  - Prevention
  - Recovery
  - Recycle

organization_status:
  - For-Profit
  - nonprofit

date_labels_required_for:
  - bakery
  - dairy
  - eggs
  - hazardous foods
  - infant formula
  - meat
  - perishables
  - sandwiches
  - shellfish
restricted_sales_on_expired_labels:
  - bakery
  - dairy
  - eggs
  - hazardous foods
  - infant formula
  - meat
  - perishables
  - sandwiches
  - shellfish
restricted_donations_on_expired_labels:
  - bakery
  - dairy
  - eggs
  - hazardous Foods
  - infant Formula
  - meat
  - perishables
  - sandwiches
  - shellfish
