# Site settings
title: ReFED | Rethink Food Waste
email: info@refed.com
description:  "A data-driven guide for businesses, government, funders, and nonprofits to collectively reduce food waste at scale. Together, we can reduce U.S. food waste by 50% by 2030."
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://refed.com" # the base hostname & protocol for your site

defaults:
- scope:
    path: solutions
  values:
    nextpage:
      url: /stakeholder
      title: Stakeholders
    prevpage:
      url: /solution
      title: Solutions
- scope:
    path: stakeholders
  values:
    nextpage:
      url: /action
      title: Action
    prevpage:
      url: /stakeholder
      title: Stakeholders

collections:
  solutions:
    output: true
    layout: default
    permalink: /solutions/:path
  stakeholders:
    output: true
    layout: default
    permalink: /stakeholders/:path


# Build settings
safe: false
source: src
markdown: kramdown

include: ["_pages"]


gems:
  - jekyll-bootstrap-sass
# - jekyll-lunr-js-search
