# Site settings
title: Your awesome title
email: your-email@domain.com
description:  Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

collections:
  solutions:
    output: true
    layout: default
    permalink: /solutions/:path
  stakeholders:
    output: true
    layout: default
    permalink: /stakeholders/:path

# permalink: /:title

# Build settings
safe: false
source: src
destination: publish
bundler_args: --without production
markdown: kramdown

include: ["_pages"]
exclude: [vendor]

gems:
- jekyll-assets


assets:
  compress:
    css: true # default - development: false, production: true
    js: true # default - development: false, production: true
  cache: .asset-cache # default: .asset-cache
  # cdn: https://cdn.example.com
  # skip_baseurl_with_cdn: false
  # skip_prefix_with_cdn: false
  prefix: "/assets"
  assets:
    - "*.png"
    - "*.jpg"
    - "*.eot"
    - "*.ttf"
    - "*.woff"
    - "*.svg"
  #   - "bundle.css"
  digest: true
  sources:
    - _assets/bower
    - _assets/css
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/fonts
    - _assets/icons
    - _assets/img
    - _assets/js
  features:
    liquid: true # default: false
    automatic_img_size: true # default: true
    automatic_img_alt : true # default: true