# Site settings
title: ReFED | Rethink Food Waste
email: info@refed.com
description:  "A data-driven guide for businesses, government, funders, and nonprofits to collectively reduce food waste at scale. Together, we can reduce U.S. food waste by 50% by 2030."
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://refed.com" # the base hostname & protocol for your site

defaults:
- type: 'solutions'
  values:
    nextpage:
      url: /stakeholder
      title: Stakeholders
    prevpage:
      url: /solution
      title: Solutions
- type: 'stakeholders'
  values:
    nextpage:
      url: /action
      title: Action
    prevpage:
      url: /stakeholder
      title: Stakeholders
- type: 'states'
  values:
    policy_data:
      date_labeling:
          overview: "lorem"
          summary: "lorem"
          link_url:
          case_studies: []
          legislation:
            - title:
              food_type: 
              purpose:
              excerpt:
              legal_citation:
          label_regulation:
            foods:
            sale_after_date: boolean
            donation_after_date: boolean
      liability_protection:
          overview: "lorem"
          summary: "lorem"
          link_url:
          case_studies: []
          legislation:
            - title:
              type:
              when:
              who:
              eligible_recipients:
              standards:
              paid_donations:
              direct_donations:
              additional_protections:
      donation_tax_incentives:
          overiew: "lorem"
          summary: "lorem"
          link_url: 
          case_studies: []
          legislation:
            - title:
              deduction_or_credit:
              benefit:
              eligible_donors:
              eligible_food:
              eligible_recipients:
      animal_feed:
          overview: "lorem"
          summary: "lorem"
          link_url:
          case_studies: []
          legislation:
            - title:
              animals_covered:
              definition_of_garbage:
              prohibitions:
              licensure_requirements:
              treatment_requirements:
              enforcement:
      organics_recycling_mandates:
          overview: "lorem"
          summary: "lorem"
          link_url:
          case_studies: []
          legislation:
            - title:
              generators_covered:
              waste_prduction:
              exemptions_for_distance:
collections:
  solutions:
    output: true
    layout: default
    permalink: /solutions/:path
  stakeholders:
    output: true
    layout: default
    permalink: /stakeholders/:path
  states:
    output: true
    layout: state
    permalink: /states/:path  


# Build settings
safe: false
source: src
markdown: kramdown

include: ["_pages"]


gems:
  - jekyll-bootstrap-sass
# - jekyll-lunr-js-search
