# Site settings
title: ReFED | Rethink Food Waste
email: info@refed.com
description:  "A data-driven guide for businesses, government, funders, and nonprofits to collectively reduce food waste at scale. Together, we can reduce U.S. food waste by 50% by 2030."
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://dev.refed.com" # the base hostname & protocol for your site

collections:
  solutions:
    output: true
    layout: default
    permalink: /solutions/:path
  stakeholders:
    output: true
    layout: default
    permalink: /stakeholders/:path
  tools:
    output: true
    layout: tool
    permalink: /tools/:path
  states:
    output: true
    layout: state
    permalink: /tools/food-waste-policy-finder/states/:path
  innovators:
    output: true
    layout: innovator
    permalink: /tools/innovator-database/:path
  articles:
    output: true
    layout: article
    permalink: /content-hub/:path

defaults:
  - 
    scope:
      type: 'states'
    values:
      layout: state
      header: "<small>U.S. Food Waste</small>Policy Finder"
      tool_url: /tools/food-waste-policy-finder/
  - 
    scope:
      type: 'innovators'
    values:
      layout: innovator
      header: "<small>The Food Waste</small>Innovator Database"
      tool_url: /tools/innovator-database/
  - 
    scope:
      type: 'solutions'
    values:
      nextpage:
        url: /stakeholder
        title: Stakeholders
      prevpage:
        url: /solution
        title: Solutions
  - 
    scope:
      type: 'stakeholders'
    values:
      nextpage:
        url: /action
        title: Action
      prevpage:
        url: /stakeholder
        title: Stakeholders






# Build settings
safe: false
source: src
markdown: kramdown

include: ["_pages"]
exclude: 
  - _tools/policy-tool/_partials


gems:
  - jekyll-last-modified-at
  - jekyll-contentblocks
# - jekyll-lunr-js-search


# Cloudcannon Editor
innovator_reach_categories: 
  - local
  - national

innovator_levels:
  - local
  - national

food_recovery_categories:
  - title: Prevention
    summary: "Prevention stops waste before it can occur, saving all the natural resources and other inputs embedded in food from going to waste as well."
  - title: Recovery
    summary: "Recovery captures edible food that would otherwise go to waste on farms or in consumer-facing businesses, and redistributes it to food insecure populations."
  - title: Recycling
    summary: "Recycling gives a higher purpose to the inedible food scraps that remain after preventing or recovering as much as possible, either as a direct source of nutrition for animals, or by converting the material into a value-added product."

organization_classifications:
  - "For-Profit"
  - "Nonprofit"

business_models:
  - "For-Profit"
  - "Nonprofit"  

innovator_categories:
  - title: Consumer Education
    summary: "Includes educational campaigns and resources that target wasted food, as well as tools and applications that enhance consumers' understanding of strategies to prevent food waste, including eating food before it spoils."
    innovator_subcategories:
      - Campaigns
      - Tools/Applications
      - Improved Inventory Management (Consumer Level)
      - Smart Refrigerator
  - title: Supply Chain and Operational Efficiency
    summary: "Tools, technologies, and systems that decrease food loss and waste in the supply chain or in food business operations."
    innovator_subcategories:
      - Cold Chain Management
      - Improved Inventory Management
      - Waste Tracking & Analytics
  - title: Shelf-Life Extension
    summary: "Any technology that physically enhances the ability of perishable food to remain fresh for longer, including food packaging."
    innovator_subcategories:
      - Ethylene Inhibitor
      - Spoilage Prevention Packaging
      - Packaging Adjustments
  - title: Secondary Marketplaces
    summary: "A secondary marketplace that connects surplus food (food that would otherwise be wasted) to buyers. This includes brick-and-mortar entities, platforms to facilitate the purchase of surplus produce from farms, and platforms to facilitate the purchase of surplus food from restaurants."    
    innovator_subcategories:
      - Brick and Mortar
      - Farm to Buyer
      - Business to Buyer
      - Business to Business
      - Consumer to Consumer
  - title: Food Product Creation
    summary: "Any commercial or nonprofit business converting edible food that is currently considered waste (e.g. surplus/cosmetically challenged produce; brewery waste; vegetable trimmings) into value-added consumer food products (e.g., juices, fruit snacks, energy bars)."
    innovator_subcategories:
      - Surplus Produce
      - Food Scraps
      - Byproducts
  - title: Donation Coordination
    summary: "An organization or technology that enables any aspect of food donation, including matching food donors with food recipients in real-time, known as 'donation matching software'."
    innovator_subcategories:
      - Donation Matching Software
      - Donation Coordinator
  - title: Donation Transportation
    summary: "An organization that is actively involved in the collection and distribution of donated food."
    innovator_subcategories:
      - Donation Transportation
      - Consumer Food Recovery
  - title: Donated Food Processing
    summary: "An organization that collects, stores, and processes donated food for distribution to food insecure populations. This includes community kitchen models and the value-added processing of donated food"
    innovator_subcategories:
      - Donation Storage & Handling
      - Community Kitchen
      - Value-Added Processing
  - title: Renewable Energy from Organics (Anaerobic Digestion)
    summary: "An organization that generates renewable energy from organic material via anaerobic digestion, both on-site or at a centralized facility."
    innovator_subcategories:
      - Centralized Anaerobic Digestion
      - Distributed Anaerobic Digestion
      - Small Scale Anaerobic Digestion
  - title: Composting
    summary: "An organization that processes food waste by composting on any scale at a designated location."
    innovator_subcategories:
      - Community Composting
      - Centralized Composting
      - Home Composting
  - title: Animal Feed
    summary: "An organization that processes food waste by feeding the material to animals."
    innovator_subcategories:
      - Livestock
      - Black Soldier Fly Larvae
  - title: On-Site Processing Solutions
    summary: "A technology that enables an organization to process its food waste on-site."
    innovator_subcategories:
      - In-Vessel Composting
      - Commercial Greywater
  - title: Specialty Recycled Products
    summary: "Any organization that is recycling inedible food waste into value-added products for consumers (e.g., dog treats; clothing) or other products like bioplastics."
    innovator_subcategories:
      - Consumer Products
      - Industrial Products
      - Agricultural Products

date_labels_required_for:
  - bakery
  - dairy
  - eggs
  - hazardous foods
  - infant formula
  - meat
  - perishables
  - sandwiches
  - shellfish
restricted_sales_on_expired_labels:
  - bakery
  - dairy
  - eggs
  - hazardous foods
  - infant formula
  - meat
  - perishables
  - sandwiches
  - shellfish
restricted_donations_on_expired_labels:
  - bakery
  - dairy
  - eggs
  - hazardous Foods
  - infant Formula
  - meat
  - perishables
  - sandwiches
  - shellfish
