---
# this ensures Jekyll reads the file
---

{% include _assets/js/libs/bootstrap-multiselect.js %}
{% include _assets/js/libs/bootstrap-tour.min.js %}
{% include _assets/js/libs/chartist.min.js %}
{% include _assets/js/libs/chartist-plugin-fill-donut.min.js %}
{% include _assets/js/libs/behaviors.js %}
{% include _assets/js/libs/jquery.cookie.js %}
{% include _assets/js/libs/jquery.form.js %}
{% include _assets/js/libs/jquery.stickit.js %}
{% include _assets/js/libs/jquery.scrollTo.js %}
{% include _assets/js/libs/jquery.localScroll.js %}
{% include _assets/js/libs/lunr.min.js %}
{% include _assets/js/libs/jquery.waypoints.min.js %}
{% include _assets/js/libs/inview.min.js %}
{% include _assets/js/plugins.js %}
{% include _assets/js/tour.js %}
{% include _assets/js/scroll.js %}
{% include _assets/js/pageState.js %}
{% include _assets/js/disabled.js %}
{% include _assets/js/tabs.js %}
{% include _assets/js/sticky.js %}
{% include _assets/js/video.js %}
{% include _assets/js/print.js %}
{% include _assets/js/lineClamp.js %}
{% include _assets/js/nav/quicknav.js %}
{% include _assets/js/nav/toolnav.js %}
{% include _assets/js/nav/pagenav.js %}
{% include _assets/js/components/share.js %}
{% include _assets/js/components/solutionCards.js %}
{% include _assets/js/components/supplyChain.js %}
{% include _assets/js/components/siteSearch.js %}
{% include _assets/js/components/pageHelp.js %}
{% include _assets/js/components/articles.js %}
{% include _assets/js/components/menuToggle.js %}
{% include _assets/js/components/toc.js %}
{% include _assets/js/components/profile.js %}
{% include _assets/js/components/download.js %}
{% include _assets/js/charts.js %}
{% include _assets/js/components/charts/cost_curve.js %}
{% include _assets/js/components/charts/reduction_chart.js %}
{% include _assets/js/components/maps/locationField.js %}
{% include _assets/js/tools/innovator-database/map.js %}
{% include _assets/js/tools/innovator-database/list.js %}
{% include _assets/js/tools/innovator-database/filters.js %}
{% include _assets/js/tools/innovator-database/analysis.js %}
{% include _assets/js/tools/innovator-database/about.js %}
{% include _assets/js/tools/food-waste-policy-finder/map.js %}
{% include _assets/js/tools/spotlight-on-date-labeling/quiz.js %}
{% include _assets/js/tools/spotlight-on-date-labeling/carousel-date-label.js %}
{% include _assets/js/main.js %}