# Site settings
title: ReFED | Rethink Food Waste
email: info@refed.com
description: 'A data-driven guide for businesses, government, funders, and nonprofits to collectively reduce food waste at scale. Together, we can reduce U.S. food waste by 50% by 2030.'
baseurl: '' # the subpath of your site, e.g. /blog
url: 'https://victorious-shoe.cloudvent.net'
# url: 'http://www.refed.com' # the base hostname & protocol for your site
permalink: pretty

# Collections
collections:
  testimonials:
    output: false
  press:
    output: false
    layout: post
    sort_by: date
  newsletters:
    output: true
  team_members:
    output: false
  casestudies:
    output: true

defaults:
  - scope:
      type: "posts"
    values:
      layout: "blog"
      author: "unknown"
      location: Minneapolis, MN
      hero:
        preheader: Blog
      

# Build settings
safe: false
sass:
  # style: compressed
  sass_dir: _scss

plugins:
  - jekyll-sitemap

_array_structures:
  navigation:
    - label: Navigation
      icon: link
      value:
        link:
        title:
        links:
  links:
    - label: Links
      icon: link
      value:
        title:
        link:
        links:
  page_sections:
    - label: Single Column
      icon: article
      value:
        _type: single_column
        section_html:
    - label: Card Grid
      icon: web
      value:
        _type: card_grid
        title:
        cards:
    - label: Testimonials
      icon: format_quote
      value:
        _type: testimonials
        testimonials:
    - label: Hero
      icon: panorama
      value:
        _type: hero
        title:
        description_html:
        image:
        link:
        link_text:
  testimonials:
    - label: Testimonial
      icon: format_quote
      value:
        text:
        author:
        cite:
        image:  
  cards:
    - label: Cards
      icon: view_column
      value: 
        title:
        text:
        featured_image:
        link:
  images:
    - label: Images
      icon: insert_photo
      value:
        image:
        title:
  hero:
    - label: Hero
      icon: panorama
      value:
        title:
        description_html:
        image:
        link:
        link_text:        


_comments:
  cards: page section for card grid that is not related to a collection
        
placeholder_image: 'https://via.placeholder.com/1000'


# Cloudcannon Editor
