source "http://rubygems.org"
ruby "2.6.2"
gem "jekyll"
gem 'sassc'
gem 'scss_lint', '0.57.0'

gem 'redcarpet'
gem 'html-proofer'
gem 'uglifier'
gem 'autoprefixer-rails'

group :jekyll_plugins do
  gem 'jekyll-sitemap'
  gem 'jekyll-contentblocks'
  gem 'jekyll-minibundle'
  gem 'jekyll-last-modified-at'
  gem 'pagemaster'
end